apiVersion: v1
kind: Service
metadata:
  namespace: cldinf-app
  name: cldinf-db
  labels:
    app: cldinf-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: cldinf-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cldinf-db
  namespace: cldinf-app
spec:
  selector:
    matchLabels:
      app: cldinf-db
  template:
    metadata:
      labels:
        app: cldinf-db
    spec:
      containers:
        - name: cldinf-database
          image: postgres:9.6.2
          imagePullPolicy: "IfNotPresent"
          env:
           - name: PG_USER
             valueFrom:
               configMapKeyRef:
                 name: db-config
                 key: PG_USER
           - name: PG_PASSWORD
             valueFrom:
               configMapKeyRef:
                 name: db-config
                 key: PG_PASSWORD
           - name: PG_DATABASE
             valueFrom:
               configMapKeyRef:
                 name: db-config
                 key: PG_DATABASE
           - name: PG_HOST
             valueFrom:
               configMapKeyRef:
                 name: db-config
                 key: PG_HOST
           - name: PG_PORT
             valueFrom:
               configMapKeyRef:
                 name: db-config
                 key: PG_PORT
           - name: LOG_PATH
             valueFrom:
               configMapKeyRef:
                 name: db-config
                 key: LOG_PATH  
           - name: DEBUG
             value: "true"
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            -  name: postgre-storge
               mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgre-storge
          persistentVolumeClaim:
            claimName: pvc-cldinf-app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: cldinf-app 
  name: pvc-cldinf-app
  labels:
    app: pvc-cldinf-app
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 1Gi
  storageClassName: localstorage
  volumeName: pv-cldinf-app
---
apiVersion: v1
kind: PersistentVolume
metadata:
    namespace: cldinf-app
    name: pv-cldinf-app
    labels:
        app: pv-cldinf-app
        type: local
spec:
     accessModes:
        - ReadWriteOnce
     capacity:
        storage: 1Gi
     hostPath:
         path: /data/cldinf-db-postgres
     storageClassName:
         localstorage
