apiVersion: v1
kind: Service
metadata:
  namespace: cldinf-app
  name: cldinf-web
  labels:
    app: cldinf-web
spec: 
  type: NodePort
  selector:
    app: cldinf-web
    tier: frontend
    track: stable   
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cldinf-app
  name: cldinf-web
  labels:
    app: cldinf-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cldinf-web
      tier: frontend
      track: stable
  template:
    metadata:
        labels:
          app: cldinf-web
          tier: frontend
          track: stable
    spec:
      containers:
        - name: cldinf-web
          env:
           - name: PORT
             valueFrom:
               configMapKeyRef:
                 name: web-config
                 key: PORT
           - name: MODULE_NAME
             valueFrom:
               configMapKeyRef:
                 name: web-config
                 key: MODULE_NAME
           - name: GROUPE_NAME
             valueFrom:
               configMapKeyRef:
                 name: web-config
                 key: GROUPE_NAME
           - name: API_HOST
             valueFrom:
               configMapKeyRef:
                 name: web-config
                 key: API_HOST
           - name: API_PORT
             valueFrom:
               configMapKeyRef:
                 name: web-config
                 key: API_PORT
          image: registry.gitlab.ost.ch:45023/ins-stud/cldinf/resources/web:1.0.0
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx", "-s", "quit"]
          ports:
            - name: http
              containerPort: 80
      imagePullSecrets:
        - name: regcred

#nginx-controller
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-ingress
  template:
    metadata:
      labels:
        name: nginx-ingress
    spec:
      containers:
        - name: nginx-ingress-controller
          image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.27.0
          args:
            - /nginx-ingress-controller
            - --configmap=$(POD_NAMESPACE)/nginx-configuration
          env:
            - name: POD_NAME
              valueFrom: 
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
#nignx-svc
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  type: NodePort
  ports: 
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    name: nginx-ingress

      