apiVersion: v1
kind: Service
metadata:
  namespace: cldinf-app
  name: cldinf-web
  labels:
    app: cldinf-web
spec: 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  externalIPs:
  - 10.18.8.200
  selector:
    app: cldinf-web
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cldinf-app
  name: cldinf-web
  labels:
    app: cldinf-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cldinf-web
  template:
    metadata:
        labels:
          app: cldinf-web
    spec:
      containers:
        - name: cldinf-web
          env:
           - name: PORT
             valueFrom:
               configMapKeyRef:
                 name: web-config
                 key: PORT
           - name: MODULE_NAME
             valueFrom:
               configMapKeyRef:
                 name: web-config
                 key: MODULE_NAME
           - name: GROUPE_NAME
             valueFrom:
               configMapKeyRef:
                 name: web-config
                 key: GROUPE_NAME
           - name: API_HOST
             valueFrom:
               configMapKeyRef:
                 name: web-config
                 key: API_HOST
           - name: API_PORT
             valueFrom:
               configMapKeyRef:
                 name: web-config
                 key: API_PORT
          image: registry.gitlab.ost.ch:45023/ins-stud/cldinf/resources/web:1.0.0
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx", "-s", "quit"]
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
