apiVersion: extensions/v1beta1
kind: Ingress
metadata: 
  name: cldinf-ingress
  namespace: cldinf-app
spec:
  ingressClassName: nginx-public
  tls:
  - hosts:
    - cldinf-k8s-g5.network.garden
    secretName: cldinf-web-tls
  rules:
  - host: cldinf-k8s-g5.network.garden
    http:
      paths:
      - path: /
        backend:
            serviceName: cldinf-api
            servicePort: 80