apiVersion: v1
kind: Service
metadata:
  name: cldinf-api
  namespace: cldinf-app
  labels:
    app: cldinf-api
spec: 
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: cldinf-api
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cldinf-app
  name: cldinf-api
  labels:
    app: cldinf-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cldinf-api
      tier: backend
      track: stable
  template:
    metadata:
        labels:
          app: cldinf-api
          tier: backend
          track: stable
    spec:
      containers:
        - name: cldinf-api
          env:
           - name: PG_USER
             valueFrom:
               configMapKeyRef:
                 name: db-config
                 key: PG_USER
           - name: PG_PASSWORD
             valueFrom:
               configMapKeyRef:
                 name: db-config
                 key: PG_PASSWORD
           - name: PG_DATABASE
             valueFrom:
               configMapKeyRef:
                 name: db-config
                 key: PG_DATABASE
           - name: PG_HOST
             valueFrom:
               configMapKeyRef:
                 name: db-config
                 key: PG_HOST
           - name: PG_PORT
             valueFrom:
               configMapKeyRef:
                 name: db-config
                 key: PG_PORT
           - name: LOG_PATH
             valueFrom:
               configMapKeyRef:
                 name: api-config
                 key: LOG_PATH
           - name: DEBUG
             valueFrom:
               configMapKeyRef:
                 name: api-config
                 key: DEBUG                                                                     
          image: registry.gitlab.ost.ch:45023/ins-stud/cldinf/resources/api:1.0.0
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx", "-s", "quit"]
          ports:
            - name: http
              containerPort: 8000
      imagePullSecrets:
        - name: regcred
      resources:
        requests:
          memory: "64Mi"
          cpu: "200m"
        limits:
          memory: "128Mi"
          cpu: "400m"

