apiVersion: v1
kind: PersistentVolume
apiVersion: v1
metadata:
    name: pv-test
    labels:
        type: local
spec:
     capacity:
        storage: 1Gi
     accessModes:
     -  ReadWriteOnce
     hostPath:
         path: “/mnt/data”
     storageClassName:
         localstorage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pvc-test
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 100Mi
  storageClassName: localstorage

