kind: PersistentVolume
apiVersion: v1
metadata:
    name: pv-cldinf-app
    namespace: cldinf-app
    labels:
        type: local
spec:
     capacity:
        storage: 1Gi
     accessModes:
     -  ReadWriteOnce
     hostPath:
         path: “/mnt/data”
     storageClassName:
         localstorage
