apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pvc-cldinf-app
  namespace: cldinf-app
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 200Mi
  storageClassName: localstorage
