
apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe-demo
spec:
  containers:
  - name: liveness-probe-demo
    image: k8s.gcr.io/goproxy:0.1
    ports:
    - containerPort: 8080
    livenessProbe:
    tcpSocket:
        port: 8080
    initialDelaySeconds: 5
    periodSeconds: 15
    failureThreshold: 1