apiVersion: v1
kind: Pod
metadata:
  namespace: cldinf-app
  labels:
    app: cldinf-monitoring
  name: liveness-http
spec:
  imagePullSecrets:
    - name: regcred
  containers:
    image: registry.gitlab.ost.ch:45023/ins-stud/cldinf/resources/api:1.0.0
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3