apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: nginx
  namespace: metallb-system
spec:
  addresses:
    - 10.18.8.200/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: nginx
  namespace: metallb-system
spec:
  ipAddressPools:
    - nginx
  nodeSelectors:
    - matchLabels:
        ingress: "true"
